// js/abilities.js - Game-accurate abilities for all 151 Gen 1 Pokemon

// Pokemon ID → ability name
export const POKEMON_ABILITIES = {
    1: 'Overgrow', 2: 'Overgrow', 3: 'Overgrow',
    4: 'Blaze', 5: 'Blaze', 6: 'Blaze',
    7: 'Torrent', 8: 'Torrent', 9: 'Torrent',
    10: 'Compound Eyes', 11: 'Compound Eyes', 12: 'Compound Eyes',
    13: 'Poison Point', 14: 'Poison Point', 15: 'Poison Point',
    16: 'Keen Eye', 17: 'Keen Eye', 18: 'Keen Eye',
    19: 'Guts', 20: 'Guts',
    21: 'Keen Eye', 22: 'Keen Eye',
    23: 'Intimidate', 24: 'Intimidate',
    25: 'Static', 26: 'Static',
    27: 'Sand Veil', 28: 'Sand Veil',
    29: 'Poison Point', 30: 'Poison Point', 31: 'Poison Point',
    32: 'Poison Point', 33: 'Poison Point', 34: 'Poison Point',
    35: 'Magic Guard', 36: 'Magic Guard',
    37: 'Flash Fire', 38: 'Flash Fire',
    39: 'Thick Fat', 40: 'Thick Fat',
    41: 'Inner Focus', 42: 'Inner Focus',
    43: 'Chlorophyll', 44: 'Chlorophyll', 45: 'Chlorophyll',
    46: 'Chlorophyll', 47: 'Chlorophyll',
    48: 'Compound Eyes', 49: 'Compound Eyes',
    50: 'Arena Trap', 51: 'Arena Trap',
    52: 'Limber', 53: 'Limber',
    54: 'Damp', 55: 'Damp',
    56: 'Guts', 57: 'Guts',
    58: 'Flash Fire', 59: 'Flash Fire',
    60: 'Water Absorb', 61: 'Water Absorb', 62: 'Water Absorb',
    63: 'Synchronize', 64: 'Synchronize', 65: 'Synchronize',
    66: 'Guts', 67: 'Guts', 68: 'Guts',
    69: 'Chlorophyll', 70: 'Chlorophyll', 71: 'Chlorophyll',
    72: 'Poison Point', 73: 'Poison Point',
    74: 'Sturdy', 75: 'Sturdy', 76: 'Sturdy',
    77: 'Flash Fire', 78: 'Flash Fire',
    79: 'Own Tempo', 80: 'Own Tempo',
    81: 'Sturdy', 82: 'Sturdy',
    83: 'Keen Eye',
    84: 'Keen Eye', 85: 'Keen Eye',
    86: 'Thick Fat', 87: 'Thick Fat',
    88: 'Sticky Hold', 89: 'Sticky Hold',
    90: 'Shell Armor', 91: 'Shell Armor',
    92: 'Levitate', 93: 'Levitate', 94: 'Levitate',
    95: 'Sturdy',
    96: 'Insomnia', 97: 'Insomnia',
    98: 'Shell Armor', 99: 'Shell Armor',
    100: 'Static', 101: 'Static',
    102: 'Chlorophyll', 103: 'Chlorophyll',
    104: 'Rock Head', 105: 'Rock Head',
    106: 'Limber',
    107: 'Inner Focus',
    108: 'Own Tempo',
    109: 'Levitate', 110: 'Levitate',
    111: 'Rock Head', 112: 'Rock Head',
    113: 'Natural Cure',
    114: 'Chlorophyll',
    115: 'Scrappy',
    116: 'Swift Swim', 117: 'Swift Swim',
    118: 'Swift Swim', 119: 'Swift Swim',
    120: 'Natural Cure', 121: 'Natural Cure',
    122: 'Soundproof',
    123: 'Technician',
    124: 'Oblivious',
    125: 'Static',
    126: 'Flame Body',
    127: 'Hyper Cutter',
    128: 'Intimidate',
    129: 'Swift Swim',
    130: 'Intimidate',
    131: 'Water Absorb',
    132: 'Imposter',
    133: 'Adaptability',
    134: 'Water Absorb',
    135: 'Volt Absorb',
    136: 'Flash Fire',
    137: 'Adaptability',
    138: 'Swift Swim', 139: 'Swift Swim',
    140: 'Swift Swim', 141: 'Swift Swim',
    142: 'Rock Head',
    143: 'Thick Fat',
    144: 'Pressure', 145: 'Pressure', 146: 'Flame Body',
    147: 'Marvel Scale', 148: 'Marvel Scale', 149: 'Inner Focus',
    150: 'Pressure', 151: 'Synchronize',
};

export const ABILITY_EFFECTS = {
    'Overgrow':      { description: '+50% Grass damage below 33% HP' },
    'Blaze':         { description: '+50% Fire damage below 33% HP' },
    'Torrent':       { description: '+50% Water damage below 33% HP' },
    'Guts':          { description: '+50% physical damage when statused' },
    'Adaptability':  { description: 'STAB is 2x instead of 1.5x' },
    'Technician':    { description: 'Moves with power <=60 deal 1.5x' },
    'Hyper Cutter':  { description: 'Attack cannot be lowered' },
    'Static':        { description: '30% chance to paralyze attacker' },
    'Poison Point':  { description: '30% chance to poison attacker' },
    'Flame Body':    { description: '30% chance to burn attacker' },
    'Levitate':      { description: 'Immune to Ground damage' },
    'Flash Fire':    { description: 'Immune to Fire; boosts own Fire damage' },
    'Water Absorb':  { description: 'Immune to Water; heals instead' },
    'Volt Absorb':   { description: 'Immune to Electric; heals instead' },
    'Damp':          { description: 'Nullifies self-destruct moves nearby' },
    'Soundproof':    { description: '50% chance to resist status moves' },
    'Thick Fat':     { description: 'Halves Fire and Ice damage taken' },
    'Shell Armor':   { description: 'Cannot be critically hit' },
    'Sturdy':        { description: 'Survives first lethal hit at 1 HP' },
    'Marvel Scale':  { description: '+50% defense when statused' },
    'Magic Guard':   { description: 'Immune to DOT damage' },
    'Sand Veil':     { description: '10% dodge chance' },
    'Insomnia':      { description: 'Immune to sleep' },
    'Limber':        { description: 'Immune to paralysis' },
    'Own Tempo':     { description: 'Immune to confusion' },
    'Oblivious':     { description: 'Immune to confusion and sleep' },
    'Natural Cure':  { description: 'Cures status below 50% HP' },
    'Chlorophyll':   { description: 'Double speed in sun' },
    'Swift Swim':    { description: 'Double speed in rain' },
    'Intimidate':    { description: 'Lowers nearby Attack on entry' },
    'Synchronize':   { description: 'Mirrors status back to attacker' },
    'Pressure':      { description: 'Enemies attack 20% slower' },
    'Keen Eye':      { description: 'Immune to accuracy debuffs' },
    'Inner Focus':   { description: 'Immune to confusion; +10% energy' },
    'Arena Trap':    { description: 'Lowers nearby Speed on entry' },
    'Sticky Hold':   { description: 'Stats cannot be lowered' },
    'Scrappy':       { description: 'Normal/Fighting hit Ghost types' },
    'Rock Head':     { description: 'No recoil damage' },
    'Compound Eyes': { description: 'Status moves always land' },
    'Imposter':      { description: "Copies first target's types & stats" },
};

export function getAbility(pokemonId) {
    return POKEMON_ABILITIES[pokemonId] || null;
}

export function getAbilityEffect(abilityName) {
    return ABILITY_EFFECTS[abilityName] || null;
}
